TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += PMXXX.db
DB += PMXXX.proto

#=======================================
include $(TOP)/configure/RULES
